### ISSUE TITLE
The browser is wrongly maximized and the "Blipz" doorhanger redisplayed if the "Minimize" button is clicked while the browser is unfocused

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/webcompat-blipz-experiment#187]
[Affected versions]:
- Firefox 63.0.1 Build ID - 20181030165643
- Firefox 64.0b6 Build ID - 20181101155334

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a new Firefox profile.
- Have the "extensions.webcompat-blipz-experiment.variation" string set to "little-sentiment" in the "about:config" page;
- Have the latest version of the "blipz" add-on (2.0.1) installed from here.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to "https://www.youtube.com/" and wait ~60 seconds.
3. Open a new tab and switch back to the "YouTube" one 
4. Unfocus the browser and click the "Minimize" button.
5. Observe the behavior.
 
[Expected result]:
- The browser is minimized.

[Actual result]:
- Initially, the browser is minimized but is quickly brought back and the "Blipz" doorhanger redisplayed.

[Notes]:
- It seems that this behavior is a side effect of issue [#150](https://github.com/mozilla/webcompat-blipz-experiment/issues/150).
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/48009793-0fce0680-e125-11e8-9eae-0131f35ab13b.gif)

**Comment by miketaylr** [comment]
Weird bug, nice find. It feels a bit edge-casey, given STR.

**Comment by miketaylr** [comment]
(tom will take a look, nonetheless)

**Comment by wisniewskit** [comment]
A fix is pending review, will be in the next signed build.

**Comment by miketaylr** [comment]
Should be fixed by https://github.com/mozilla/webcompat-blipz-experiment/commit/c0475680bf85aed3c7d5a20a0f2c3bea340d1b9d.

**Comment by Softvision-AndreeaCupsa** [comment]
This issue is still reproducible with the latest build from [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1490261#c43) on Firefox Release 63.0.1 and Beta 64.0b7 on Windows 10 x64, Mac 10.13.3 and Ubuntu 18.4. 
Considering this I will reopen this issue.

**Comment by wisniewskit** [comment]
I cannot reproduce this on my Windows 10 laptop, OSX laptop, or Linux desktop. The window minimizes just fine, given the STR, or in any way I try to minimize. Either it has been fixed since v2.0.3, or it isn't easy enough to reproduce for me to feel it's worth blocking this version on.
